name: Build PowerShellLogging Module
on: 
  workflow_dispatch:
  
jobs:
  build:
    name: BuildModule
    runs-on: windows-latest
    
    steps:
      - name: SetupGitVersion
        uses: StanleyGoldman/setup-gitversion@v1.0.1
          
      - name: Checkout-repo
        uses: actions/checkout@v3
      
      - name: script
        shell: pwsh
        run: .\Build -Version $(gitversion -showvariable nugetversion)

      - name: release 
        uses: actions/upload-artifact@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Module/PowerShellLogging/*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
