name: Build PowerShellLogging Module
on: 
  workflow_dispatch:
  
jobs:
  build:
    name: Build Module
    runs-on: windows-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Install powershell
        uses: cakhanif/action-install-powershell@v1
 
      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.3
        with:
          script: Build.ps1
